  //SHOP ACTION TYPES

  export const BUY_CAKE = 'BUY_CAKE';
  export const BUY_ICECREAM = 'BUY_ICECREAM';
  export const RESTOCK_CAKE = 'RESTOCK_CAKE';
  export const RESTOCK_ICECREAM = 'RESTOCK_ICECREAM';
  export const RESTOCK_CAKE_FROM_INPUT = 'RESTOCK_CAKE_FROM_INPUT';
  export const RESTOCK_ICE_CREAM_FROM_INPUT = 'RESTOCK_ICE_CREAM_FROM_INPUT';

  // API ACTION TYPES
  export const FETCH_API_LOADING = 'FETCH_API_LOADING';
  export const FETCH_API_SUCCESS = 'FETCH_API_SUCCESS';
  export const FETCH_API_FAIL = 'FETCH_API_FAIL';

  